#!/usr/bin/env python

import click

@click.group()
def servant():
    """Command line interface for Servant virtual machine."""
    pass

@servant.command()
def up(**kwargs):
    pass

@servant.command()
def down(**kwargs):
    pass

@servant.command()
def reboot(**kwargs):
    pass

@servant.command()
def reload(**kwargs):
    pass

@servant.command()
def services(**kwargs):
    pass

@servant.group()
def projects(**kwargs):
    pass

if __name__ == '__main__':
    servant()
