#!/usr/bin/env python

import click
import os
import json
import sys

configuration_file = os.path.expanduser("~/.servant-cli.json")

# Try to load configuration file
if os.path.isfile(configuration_file):
  with open(configuration_file, 'r') as f:
    config = json.load(f)
else:
  print "Couldn't find configuration file \"" + configuration_file + "\""
  sys.exit(1)

@click.group()
def servant():
    """Command line interface for Servant - the Vagrant based web-development virtual machine."""
    pass

@servant.command()
def up(**kwargs):
    pass

@servant.command()
def down(**kwargs):
    pass

@servant.command()
def reboot(**kwargs):
    pass

@servant.command()
def reload(**kwargs):
    pass

@servant.command()
def services(**kwargs):
    pass

@servant.group()
def projects(**kwargs):
    pass

@servant.command()
def ssh(**kwargs):
    pass

if __name__ == '__main__':
    servant()
